---
title: "Conda Demo"
author: "Katie Birchard"
date: '2022-08-02'
output: html_document
---

Updated rsyncrosim functions:
* session()
* ssimLibrary()

New rsyncrosim functions:
* installConda()
* useConda()
* condaFilepath()

Load rsyncrosim library
```{r}
library(rsyncrosim)
```


Install a Package that uses Conda environments
```{r}
addPackage("c:/Users/birch/OneDrive/Desktop/wisdm.ssimpkg")
```

Start an rsyncrosim Session and set the Conda Filepath
```{r}
?session

mySession <- session()

?condaFilepath

condaFilepath(mySession)

mySession <- session(condaFilepath = "C:/Users/birch/miniconda3")
condaFilepath(mySession)

condaFilepath(mySession) <- NULL
condaFilepath(mySession)
```


Create a Library and specify whether to use Conda
```{r}
?ssimLibrary

myLibrary <- ssimLibrary(name = "Conda Example",
                         package = "wisdm",
                         overwrite = TRUE,
                         useConda = TRUE,
                         session = mySession)

?useConda

useConda(myLibrary)

useConda(myLibrary) <- FALSE

useConda(myLibrary)
```

Install Conda
```{r}
?installConda

installConda()
```

Try to create Library using Package again
```{r}
myLibrary <- ssimLibrary(name = "Conda Example",
                         package = "wisdm",
                         overwrite = TRUE,
                         useConda = TRUE,
                         session = mySession)

useConda(myLibrary)
```






