mySession <- session()
myLibraryName <- file.path(tempdir(),"testlib.ssim")
myLibrary <- ssimLibrary(name = myLibraryName, session = mySession, package = "burnP3Plus", force = TRUE)
myProject <- project(myLibrary, project = "My Project")
myScenario <- scenario(myProject, scenario = "My Scenario")

test_that("commands work", {
  expect_equal((command(c("create", "help"))), (command("--create --help")))
  expect_equal((command(c("create", "help"))), (command(list(create = NULL, help = NULL))))
  expect_error((command(c("create", "help"))), NA)
  expect_error((command(list(installed = NULL), program = "SyncroSim.PackageManager.exe")), NA)
  expect_error((command(list(installed = NULL), program = "SyncroSim.Console.exe")), NA)
  #expect_error((command(list(installed = NULL), program = "SyncroSim.Server.exe")), NA)
  expect_error((command(list(installed = NULL), program = "SyncroSim.Multiband.exe")), NA)
  expect_error((command(list(installed = NULL), session = mySession, program = "SyncroSim.PackageManager.exe")), NA)
  expect_error((command(list(installed = NULL), session = mySession, program = "SyncroSim.PackageManager.exe", wait = FALSE)), NA)
  expect_error((command(arg = list(create = NULL, help = NULL), session = mySession, program = "SyncroSim.PackageManager.exe", wait = FALSE, progName = "test")), NA)
})

test_that("errors work", {
  expect_error(command(arg = list(installed = NULL), session = myLibrary, program = "SyncroSim.PackageManager.exe", wait = FALSE, progName = "test"))
  expect_error(command(list(installed = NULL), session = myProject, program = "SyncroSim.PackageManager.exe"))
  expect_error(command(list(installed = NULL), session = myScenario, program = "SyncroSim.PackageManager.exe", wait = FALSE))
  #expect_warning(expect_warning(expect_error(command(list(installed = NULL), session = "mySession", program = "SyncroSim.PackageManager.exe", progName = "test"))))
})
